/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Address = string;
export interface CreateOrderArgs {
  'deliveryAddress' : Address,
  'parcelPhoto' : [] | [ParcelPhoto],
  'pickupAddress' : Address,
}
export type CustomerId = Principal;
export interface DeliveryOrderInternal {
  'id' : OrderId,
  'proofPhoto' : [] | [DeliveryProofPhoto],
  'status' : OrderStatus,
  'deliveryAddress' : Address,
  'assignedRider' : [] | [RiderId],
  'customer' : CustomerId,
  'parcelPhoto' : [] | [ParcelPhoto],
  'pickupAddress' : Address,
}
export type DeliveryProofPhoto = Uint8Array;
export type OrderId = string;
export type OrderStatus = { 'assigned' : null } |
  { 'pending' : null } |
  { 'pickedUp' : null } |
  { 'delivered' : null };
export type ParcelPhoto = Uint8Array;
export type RiderId = Principal;
export type Role = { 'admin' : null } |
  { 'customer' : null } |
  { 'rider' : null };
export interface UpdateOrderStatusArgs {
  'status' : OrderStatus,
  'orderId' : OrderId,
}
export interface UserProfile { 'name' : string, 'role' : Role }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRider' : ActorMethod<[OrderId, RiderId], undefined>,
  'createOrder' : ActorMethod<[CreateOrderArgs], OrderId>,
  'getAllOrders' : ActorMethod<[], Array<DeliveryOrderInternal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[], Array<DeliveryOrderInternal>>,
  'getOrder' : ActorMethod<[OrderId], DeliveryOrderInternal>,
  'getOrdersByCustomer' : ActorMethod<
    [CustomerId],
    Array<DeliveryOrderInternal>
  >,
  'getOrdersByRider' : ActorMethod<[RiderId], Array<DeliveryOrderInternal>>,
  'getOrdersByStatus' : ActorMethod<
    [OrderStatus],
    Array<DeliveryOrderInternal>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateStatus' : ActorMethod<[UpdateOrderStatusArgs], undefined>,
  'uploadParcelPhoto' : ActorMethod<[OrderId, ParcelPhoto], undefined>,
  'uploadProofPhoto' : ActorMethod<[OrderId, DeliveryProofPhoto], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];