/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderId = IDL.Text;
export const RiderId = IDL.Principal;
export const Address = IDL.Text;
export const ParcelPhoto = IDL.Vec(IDL.Nat8);
export const CreateOrderArgs = IDL.Record({
  'deliveryAddress' : Address,
  'parcelPhoto' : IDL.Opt(ParcelPhoto),
  'pickupAddress' : Address,
});
export const DeliveryProofPhoto = IDL.Vec(IDL.Nat8);
export const OrderStatus = IDL.Variant({
  'assigned' : IDL.Null,
  'pending' : IDL.Null,
  'pickedUp' : IDL.Null,
  'delivered' : IDL.Null,
});
export const CustomerId = IDL.Principal;
export const DeliveryOrderInternal = IDL.Record({
  'id' : OrderId,
  'proofPhoto' : IDL.Opt(DeliveryProofPhoto),
  'status' : OrderStatus,
  'deliveryAddress' : Address,
  'assignedRider' : IDL.Opt(RiderId),
  'customer' : CustomerId,
  'parcelPhoto' : IDL.Opt(ParcelPhoto),
  'pickupAddress' : Address,
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'rider' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : Role });
export const UpdateOrderStatusArgs = IDL.Record({
  'status' : OrderStatus,
  'orderId' : OrderId,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRider' : IDL.Func([OrderId, RiderId], [], []),
  'createOrder' : IDL.Func([CreateOrderArgs], [OrderId], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(DeliveryOrderInternal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(DeliveryOrderInternal)], ['query']),
  'getOrder' : IDL.Func([OrderId], [DeliveryOrderInternal], ['query']),
  'getOrdersByCustomer' : IDL.Func(
      [CustomerId],
      [IDL.Vec(DeliveryOrderInternal)],
      ['query'],
    ),
  'getOrdersByRider' : IDL.Func(
      [RiderId],
      [IDL.Vec(DeliveryOrderInternal)],
      ['query'],
    ),
  'getOrdersByStatus' : IDL.Func(
      [OrderStatus],
      [IDL.Vec(DeliveryOrderInternal)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateStatus' : IDL.Func([UpdateOrderStatusArgs], [], []),
  'uploadParcelPhoto' : IDL.Func([OrderId, ParcelPhoto], [], []),
  'uploadProofPhoto' : IDL.Func([OrderId, DeliveryProofPhoto], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderId = IDL.Text;
  const RiderId = IDL.Principal;
  const Address = IDL.Text;
  const ParcelPhoto = IDL.Vec(IDL.Nat8);
  const CreateOrderArgs = IDL.Record({
    'deliveryAddress' : Address,
    'parcelPhoto' : IDL.Opt(ParcelPhoto),
    'pickupAddress' : Address,
  });
  const DeliveryProofPhoto = IDL.Vec(IDL.Nat8);
  const OrderStatus = IDL.Variant({
    'assigned' : IDL.Null,
    'pending' : IDL.Null,
    'pickedUp' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const CustomerId = IDL.Principal;
  const DeliveryOrderInternal = IDL.Record({
    'id' : OrderId,
    'proofPhoto' : IDL.Opt(DeliveryProofPhoto),
    'status' : OrderStatus,
    'deliveryAddress' : Address,
    'assignedRider' : IDL.Opt(RiderId),
    'customer' : CustomerId,
    'parcelPhoto' : IDL.Opt(ParcelPhoto),
    'pickupAddress' : Address,
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'rider' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : Role });
  const UpdateOrderStatusArgs = IDL.Record({
    'status' : OrderStatus,
    'orderId' : OrderId,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRider' : IDL.Func([OrderId, RiderId], [], []),
    'createOrder' : IDL.Func([CreateOrderArgs], [OrderId], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(DeliveryOrderInternal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(DeliveryOrderInternal)], ['query']),
    'getOrder' : IDL.Func([OrderId], [DeliveryOrderInternal], ['query']),
    'getOrdersByCustomer' : IDL.Func(
        [CustomerId],
        [IDL.Vec(DeliveryOrderInternal)],
        ['query'],
      ),
    'getOrdersByRider' : IDL.Func(
        [RiderId],
        [IDL.Vec(DeliveryOrderInternal)],
        ['query'],
      ),
    'getOrdersByStatus' : IDL.Func(
        [OrderStatus],
        [IDL.Vec(DeliveryOrderInternal)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateStatus' : IDL.Func([UpdateOrderStatusArgs], [], []),
    'uploadParcelPhoto' : IDL.Func([OrderId, ParcelPhoto], [], []),
    'uploadProofPhoto' : IDL.Func([OrderId, DeliveryProofPhoto], [], []),
  });
};

export const init = ({ IDL }) => { return []; };