/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Address = string;
export interface CreateOrderArgs {
  'customerName' : string,
  'deliveryAddress' : Address,
  'parcelPhoto' : [] | [ParcelPhoto],
  'mobileNumber' : string,
  'dropLocation' : string,
  'pickupAddress' : Address,
  'paymentType' : PaymentType,
  'parcelDescription' : string,
  'pickupLocation' : string,
}
export type CustomerId = Principal;
export interface DeliveryOrder {
  'id' : OrderId,
  'proofPhoto' : [] | [DeliveryProofPhoto],
  'customerName' : string,
  'status' : OrderStatus,
  'deliveryAddress' : Address,
  'assignedRider' : [] | [RiderId],
  'customer' : CustomerId,
  'parcelPhoto' : [] | [ParcelPhoto],
  'mobileNumber' : string,
  'dropLocation' : string,
  'pickupAddress' : Address,
  'timestamp' : Time,
  'paymentType' : PaymentType,
  'parcelDescription' : string,
  'pickupLocation' : string,
}
export interface DeliveryOrderInternal {
  'id' : OrderId,
  'proofPhoto' : [] | [DeliveryProofPhoto],
  'customerName' : string,
  'status' : OrderStatus,
  'deliveryAddress' : Address,
  'assignedRider' : [] | [RiderId],
  'customer' : CustomerId,
  'parcelPhoto' : [] | [ParcelPhoto],
  'mobileNumber' : string,
  'dropLocation' : string,
  'pickupAddress' : Address,
  'timestamp' : Time,
  'paymentType' : PaymentType,
  'parcelDescription' : string,
  'pickupLocation' : string,
}
export type DeliveryProofPhoto = Uint8Array;
export interface FullOrder {
  'id' : string,
  'proofPhoto' : [] | [string],
  'customerName' : string,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'assignedRider' : Principal,
  'customer' : Principal,
  'parcelPhoto' : [] | [ParcelPhoto],
  'mobileNumber' : string,
  'dropLocation' : string,
  'pickupAddress' : string,
  'timestamp' : Time,
  'paymentType' : { 'cash' : null } |
    { 'online' : null },
  'parcelDescription' : string,
  'pickupLocation' : string,
}
export interface FullOrderWithTimestamp {
  'id' : string,
  'proofPhoto' : [] | [DeliveryProofPhoto],
  'customerName' : string,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'assignedRider' : Principal,
  'hasProofPhoto' : boolean,
  'customer' : Principal,
  'parcelPhoto' : [] | [ParcelPhoto],
  'mobileNumber' : string,
  'dropLocation' : string,
  'proofPhotoTimestampString' : [] | [string],
  'pickupAddress' : string,
  'proofPhotoTimestamp' : [] | [Time],
  'timestamp' : Time,
  'paymentType' : { 'cash' : null } |
    { 'online' : null },
  'parcelDescription' : string,
  'pickupLocation' : string,
}
export type OrderId = string;
export type OrderStatus = { 'new' : null } |
  { 'assigned' : null } |
  { 'picked' : null } |
  { 'delivered' : null };
export type ParcelPhoto = Uint8Array;
export type PaymentType = { 'cash' : null } |
  { 'online' : null };
export type RiderId = Principal;
export interface RiderProfile {
  'id' : RiderId,
  'locationUrl' : [] | [string],
  'vehicleType' : string,
  'name' : string,
  'phoneNumber' : string,
}
export type Role = { 'admin' : null } |
  { 'customer' : null } |
  { 'rider' : null };
export type Time = bigint;
export interface UpdateOrderStatusArgs {
  'status' : OrderStatus,
  'orderId' : OrderId,
}
export interface UserProfile { 'name' : string, 'role' : Role }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRider' : ActorMethod<[Principal, string, string, string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRider' : ActorMethod<[OrderId, RiderId], undefined>,
  'assignRiderToOrder' : ActorMethod<
    [[] | [string], [] | [Principal]],
    boolean
  >,
  'assignRiderToOrderAndReturnRider' : ActorMethod<
    [[] | [string], [] | [Principal]],
    [] | [[DeliveryOrderInternal, [] | [RiderProfile]]]
  >,
  'createOrder' : ActorMethod<[CreateOrderArgs], OrderId>,
  'createOrderAndReturn' : ActorMethod<[[] | [FullOrder]], boolean>,
  'getAllAssignedOrders' : ActorMethod<[], Array<DeliveryOrder>>,
  'getAllDeliveredOrders' : ActorMethod<[], Array<DeliveryOrder>>,
  'getAllNewOrders' : ActorMethod<[], Array<DeliveryOrder>>,
  'getAllOrders' : ActorMethod<[], Array<DeliveryOrderInternal>>,
  'getAllPickedOrders' : ActorMethod<[], Array<DeliveryOrder>>,
  'getAllRiders' : ActorMethod<[], Array<RiderProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[], Array<DeliveryOrderInternal>>,
  'getOrder' : ActorMethod<[OrderId], DeliveryOrderInternal>,
  'getOrderProofPhotoWithTimestamp' : ActorMethod<
    [string],
    [] | [FullOrderWithTimestamp]
  >,
  'getOrderWithRiderInfo' : ActorMethod<
    [string],
    [] | [{ 'order' : DeliveryOrderInternal, 'rider' : [] | [RiderProfile] }]
  >,
  'getOrdersByCustomer' : ActorMethod<
    [CustomerId],
    Array<DeliveryOrderInternal>
  >,
  'getOrdersByRider' : ActorMethod<[RiderId], Array<DeliveryOrderInternal>>,
  'getOrdersByStatus' : ActorMethod<
    [OrderStatus],
    Array<DeliveryOrderInternal>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateRiderLocation' : ActorMethod<[Principal, string], boolean>,
  'updateStatus' : ActorMethod<[UpdateOrderStatusArgs], undefined>,
  'uploadParcelPhoto' : ActorMethod<[OrderId, ParcelPhoto], undefined>,
  'uploadProofPhoto' : ActorMethod<[OrderId, DeliveryProofPhoto], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];