/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface FullOrderWithTimestamp {
    id: string;
    proofPhoto?: DeliveryProofPhoto;
    customerName: string;
    status: OrderStatus;
    deliveryAddress: string;
    assignedRider: Principal;
    hasProofPhoto: boolean;
    customer: Principal;
    parcelPhoto?: ParcelPhoto;
    mobileNumber: string;
    dropLocation: string;
    proofPhotoTimestampString?: string;
    pickupAddress: string;
    proofPhotoTimestamp?: Time;
    timestamp: Time;
    paymentType: Variant_cash_online;
    parcelDescription: string;
    pickupLocation: string;
}
export interface CreateOrderArgs {
    customerName: string;
    deliveryAddress: Address;
    parcelPhoto?: ParcelPhoto;
    mobileNumber: string;
    dropLocation: string;
    pickupAddress: Address;
    paymentType: PaymentType;
    parcelDescription: string;
    pickupLocation: string;
}
export type Time = bigint;
export interface RiderProfile {
    id: RiderId;
    locationUrl?: string;
    vehicleType: string;
    name: string;
    phoneNumber: string;
}
export type Address = string;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DeliveryOrder {
    id: OrderId;
    proofPhoto?: DeliveryProofPhoto;
    customerName: string;
    status: OrderStatus;
    deliveryAddress: Address;
    assignedRider?: RiderId;
    customer: CustomerId;
    parcelPhoto?: ParcelPhoto;
    mobileNumber: string;
    dropLocation: string;
    pickupAddress: Address;
    timestamp: Time;
    paymentType: PaymentType;
    parcelDescription: string;
    pickupLocation: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type DeliveryProofPhoto = Uint8Array;
export type ParcelPhoto = Uint8Array;
export type RiderId = Principal;
export type CustomerId = Principal;
export interface FullOrder {
    id: string;
    proofPhoto?: string;
    customerName: string;
    status: OrderStatus;
    deliveryAddress: string;
    assignedRider: Principal;
    customer: Principal;
    parcelPhoto?: ParcelPhoto;
    mobileNumber: string;
    dropLocation: string;
    pickupAddress: string;
    timestamp: Time;
    paymentType: Variant_cash_online;
    parcelDescription: string;
    pickupLocation: string;
}
export interface UpdateOrderStatusArgs {
    status: OrderStatus;
    orderId: OrderId;
}
export interface DeliveryOrderInternal {
    id: OrderId;
    proofPhoto?: DeliveryProofPhoto;
    customerName: string;
    status: OrderStatus;
    deliveryAddress: Address;
    assignedRider?: RiderId;
    customer: CustomerId;
    parcelPhoto?: ParcelPhoto;
    mobileNumber: string;
    dropLocation: string;
    pickupAddress: Address;
    timestamp: Time;
    paymentType: PaymentType;
    parcelDescription: string;
    pickupLocation: string;
}
export type OrderId = string;
export interface UserProfile {
    name: string;
    role: Role;
}
export enum OrderStatus {
    new_ = "new",
    assigned = "assigned",
    picked = "picked",
    delivered = "delivered"
}
export enum Role {
    admin = "admin",
    customer = "customer",
    rider = "rider"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_cash_online {
    cash = "cash",
    online = "online"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addRider(riderId: Principal, name: string, phoneNumber: string, vehicleType: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRider(orderId: OrderId, rider: RiderId): Promise<void>;
    assignRiderToOrder(orderId: string | null, riderId: Principal | null): Promise<boolean>;
    assignRiderToOrderAndReturnRider(orderId: string | null, riderId: Principal | null): Promise<[DeliveryOrderInternal, RiderProfile | null] | null>;
    createOrder(args: CreateOrderArgs): Promise<OrderId>;
    createOrderAndReturn(order: FullOrder | null): Promise<boolean>;
    getAllAssignedOrders(): Promise<Array<DeliveryOrder>>;
    getAllDeliveredOrders(): Promise<Array<DeliveryOrder>>;
    getAllNewOrders(): Promise<Array<DeliveryOrder>>;
    getAllOrders(): Promise<Array<DeliveryOrderInternal>>;
    getAllPickedOrders(): Promise<Array<DeliveryOrder>>;
    getAllRiders(): Promise<Array<RiderProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyOrders(): Promise<Array<DeliveryOrderInternal>>;
    getOrder(orderId: OrderId): Promise<DeliveryOrderInternal>;
    getOrderProofPhotoWithTimestamp(orderId: string): Promise<FullOrderWithTimestamp | null>;
    getOrderWithRiderInfo(orderId: string): Promise<{
        order: DeliveryOrderInternal;
        rider?: RiderProfile;
    } | null>;
    getOrdersByCustomer(customerId: CustomerId): Promise<Array<DeliveryOrderInternal>>;
    getOrdersByRider(riderId: RiderId): Promise<Array<DeliveryOrderInternal>>;
    getOrdersByStatus(status: OrderStatus): Promise<Array<DeliveryOrderInternal>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateRiderLocation(riderId: Principal, locationUrl: string): Promise<boolean>;
    updateStatus(args: UpdateOrderStatusArgs): Promise<void>;
    uploadParcelPhoto(orderId: OrderId, photo: ParcelPhoto): Promise<void>;
    uploadProofPhoto(orderId: OrderId, photo: DeliveryProofPhoto): Promise<void>;
}
import type { Address as _Address, CreateOrderArgs as _CreateOrderArgs, CustomerId as _CustomerId, DeliveryOrder as _DeliveryOrder, DeliveryOrderInternal as _DeliveryOrderInternal, DeliveryProofPhoto as _DeliveryProofPhoto, FullOrder as _FullOrder, FullOrderWithTimestamp as _FullOrderWithTimestamp, OrderId as _OrderId, OrderStatus as _OrderStatus, ParcelPhoto as _ParcelPhoto, PaymentType as _PaymentType, RiderId as _RiderId, RiderProfile as _RiderProfile, Role as _Role, Time as _Time, UpdateOrderStatusArgs as _UpdateOrderStatusArgs, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addRider(arg0: Principal, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addRider(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRider(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRider(arg0: OrderId, arg1: RiderId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRider(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRider(arg0, arg1);
            return result;
        }
    }
    async assignRiderToOrder(arg0: string | null, arg1: Principal | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRiderToOrder(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRiderToOrder(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRiderToOrderAndReturnRider(arg0: string | null, arg1: Principal | null): Promise<[DeliveryOrderInternal, RiderProfile | null] | null> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRiderToOrderAndReturnRider(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRiderToOrderAndReturnRider(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrder(arg0: CreateOrderArgs): Promise<OrderId> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_CreateOrderArgs_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_CreateOrderArgs_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createOrderAndReturn(arg0: FullOrder | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrderAndReturn(to_candid_opt_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrderAndReturn(to_candid_opt_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllAssignedOrders(): Promise<Array<DeliveryOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssignedOrders();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssignedOrders();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDeliveredOrders(): Promise<Array<DeliveryOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeliveredOrders();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeliveredOrders();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNewOrders(): Promise<Array<DeliveryOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNewOrders();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNewOrders();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<DeliveryOrderInternal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPickedOrders(): Promise<Array<DeliveryOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPickedOrders();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPickedOrders();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRiders(): Promise<Array<RiderProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRiders();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRiders();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(): Promise<Array<DeliveryOrderInternal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<DeliveryOrderInternal> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_DeliveryOrderInternal_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_DeliveryOrderInternal_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderProofPhotoWithTimestamp(arg0: string): Promise<FullOrderWithTimestamp | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderProofPhotoWithTimestamp(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderProofPhotoWithTimestamp(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderWithRiderInfo(arg0: string): Promise<{
        order: DeliveryOrderInternal;
        rider?: RiderProfile;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderWithRiderInfo(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderWithRiderInfo(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByCustomer(arg0: CustomerId): Promise<Array<DeliveryOrderInternal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByCustomer(arg0);
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByCustomer(arg0);
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByRider(arg0: RiderId): Promise<Array<DeliveryOrderInternal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByRider(arg0);
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByRider(arg0);
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByStatus(arg0: OrderStatus): Promise<Array<DeliveryOrderInternal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n34(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n34(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n53(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n53(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateRiderLocation(arg0: Principal, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRiderLocation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRiderLocation(arg0, arg1);
            return result;
        }
    }
    async updateStatus(arg0: UpdateOrderStatusArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStatus(to_candid_UpdateOrderStatusArgs_n57(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStatus(to_candid_UpdateOrderStatusArgs_n57(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadParcelPhoto(arg0: OrderId, arg1: ParcelPhoto): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadParcelPhoto(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadParcelPhoto(arg0, arg1);
            return result;
        }
    }
    async uploadProofPhoto(arg0: OrderId, arg1: DeliveryProofPhoto): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProofPhoto(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProofPhoto(arg0, arg1);
            return result;
        }
    }
}
function from_candid_DeliveryOrderInternal_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryOrderInternal): DeliveryOrderInternal {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_DeliveryOrder_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryOrder): DeliveryOrder {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_FullOrderWithTimestamp_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FullOrderWithTimestamp): FullOrderWithTimestamp {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentType): PaymentType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_RiderProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiderProfile): RiderProfile {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[_DeliveryOrderInternal, [] | [_RiderProfile]]]): [DeliveryOrderInternal, RiderProfile | null] | null {
    return value.length === 0 ? null : from_candid_tuple_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DeliveryProofPhoto]): DeliveryProofPhoto | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RiderId]): RiderId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ParcelPhoto]): ParcelPhoto | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RiderProfile]): RiderProfile | null {
    return value.length === 0 ? null : from_candid_RiderProfile_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FullOrderWithTimestamp]): FullOrderWithTimestamp | null {
    return value.length === 0 ? null : from_candid_FullOrderWithTimestamp_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        order: _DeliveryOrderInternal;
        rider: [] | [_RiderProfile];
    }]): {
    order: DeliveryOrderInternal;
    rider?: RiderProfile;
} | null {
    return value.length === 0 ? null : from_candid_record_n52(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    proofPhoto: [] | [_DeliveryProofPhoto];
    customerName: string;
    status: _OrderStatus;
    deliveryAddress: _Address;
    assignedRider: [] | [_RiderId];
    customer: _CustomerId;
    parcelPhoto: [] | [_ParcelPhoto];
    mobileNumber: string;
    dropLocation: string;
    pickupAddress: _Address;
    timestamp: _Time;
    paymentType: _PaymentType;
    parcelDescription: string;
    pickupLocation: string;
}): {
    id: OrderId;
    proofPhoto?: DeliveryProofPhoto;
    customerName: string;
    status: OrderStatus;
    deliveryAddress: Address;
    assignedRider?: RiderId;
    customer: CustomerId;
    parcelPhoto?: ParcelPhoto;
    mobileNumber: string;
    dropLocation: string;
    pickupAddress: Address;
    timestamp: Time;
    paymentType: PaymentType;
    parcelDescription: string;
    pickupLocation: string;
} {
    return {
        id: value.id,
        proofPhoto: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.proofPhoto)),
        customerName: value.customerName,
        status: from_candid_OrderStatus_n17(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        assignedRider: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.assignedRider)),
        customer: value.customer,
        parcelPhoto: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.parcelPhoto)),
        mobileNumber: value.mobileNumber,
        dropLocation: value.dropLocation,
        pickupAddress: value.pickupAddress,
        timestamp: value.timestamp,
        paymentType: from_candid_PaymentType_n21(_uploadFile, _downloadFile, value.paymentType),
        parcelDescription: value.parcelDescription,
        pickupLocation: value.pickupLocation
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RiderId;
    locationUrl: [] | [string];
    vehicleType: string;
    name: string;
    phoneNumber: string;
}): {
    id: RiderId;
    locationUrl?: string;
    vehicleType: string;
    name: string;
    phoneNumber: string;
} {
    return {
        id: value.id,
        locationUrl: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.locationUrl)),
        vehicleType: value.vehicleType,
        name: value.name,
        phoneNumber: value.phoneNumber
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _Role;
}): {
    name: string;
    role: Role;
} {
    return {
        name: value.name,
        role: from_candid_Role_n43(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    proofPhoto: [] | [_DeliveryProofPhoto];
    customerName: string;
    status: _OrderStatus;
    deliveryAddress: string;
    assignedRider: Principal;
    hasProofPhoto: boolean;
    customer: Principal;
    parcelPhoto: [] | [_ParcelPhoto];
    mobileNumber: string;
    dropLocation: string;
    proofPhotoTimestampString: [] | [string];
    pickupAddress: string;
    proofPhotoTimestamp: [] | [_Time];
    timestamp: _Time;
    paymentType: {
        cash: null;
    } | {
        online: null;
    };
    parcelDescription: string;
    pickupLocation: string;
}): {
    id: string;
    proofPhoto?: DeliveryProofPhoto;
    customerName: string;
    status: OrderStatus;
    deliveryAddress: string;
    assignedRider: Principal;
    hasProofPhoto: boolean;
    customer: Principal;
    parcelPhoto?: ParcelPhoto;
    mobileNumber: string;
    dropLocation: string;
    proofPhotoTimestampString?: string;
    pickupAddress: string;
    proofPhotoTimestamp?: Time;
    timestamp: Time;
    paymentType: Variant_cash_online;
    parcelDescription: string;
    pickupLocation: string;
} {
    return {
        id: value.id,
        proofPhoto: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.proofPhoto)),
        customerName: value.customerName,
        status: from_candid_OrderStatus_n17(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        assignedRider: value.assignedRider,
        hasProofPhoto: value.hasProofPhoto,
        customer: value.customer,
        parcelPhoto: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.parcelPhoto)),
        mobileNumber: value.mobileNumber,
        dropLocation: value.dropLocation,
        proofPhotoTimestampString: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.proofPhotoTimestampString)),
        pickupAddress: value.pickupAddress,
        proofPhotoTimestamp: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.proofPhotoTimestamp)),
        timestamp: value.timestamp,
        paymentType: from_candid_variant_n22(_uploadFile, _downloadFile, value.paymentType),
        parcelDescription: value.parcelDescription,
        pickupLocation: value.pickupLocation
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    order: _DeliveryOrderInternal;
    rider: [] | [_RiderProfile];
}): {
    order: DeliveryOrderInternal;
    rider?: RiderProfile;
} {
    return {
        order: from_candid_DeliveryOrderInternal_n14(_uploadFile, _downloadFile, value.order),
        rider: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.rider))
    };
}
function from_candid_tuple_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_DeliveryOrderInternal, [] | [_RiderProfile]]): [DeliveryOrderInternal, RiderProfile | null] {
    return [
        from_candid_DeliveryOrderInternal_n14(_uploadFile, _downloadFile, value[0]),
        from_candid_opt_n23(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    assigned: null;
} | {
    picked: null;
} | {
    delivered: null;
}): OrderStatus {
    return "new" in value ? OrderStatus.new : "assigned" in value ? OrderStatus.assigned : "picked" in value ? OrderStatus.picked : "delivered" in value ? OrderStatus.delivered : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    online: null;
}): Variant_cash_online {
    return "cash" in value ? Variant_cash_online.cash : "online" in value ? Variant_cash_online.online : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    customer: null;
} | {
    rider: null;
}): Role {
    return "admin" in value ? Role.admin : "customer" in value ? Role.customer : "rider" in value ? Role.rider : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DeliveryOrder>): Array<DeliveryOrder> {
    return value.map((x)=>from_candid_DeliveryOrder_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DeliveryOrderInternal>): Array<DeliveryOrderInternal> {
    return value.map((x)=>from_candid_DeliveryOrderInternal_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RiderProfile>): Array<RiderProfile> {
    return value.map((x)=>from_candid_RiderProfile_n24(_uploadFile, _downloadFile, x));
}
function to_candid_CreateOrderArgs_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateOrderArgs): _CreateOrderArgs {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_FullOrder_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FullOrder): _FullOrder {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentType): _PaymentType {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateOrderStatusArgs_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateOrderStatusArgs): _UpdateOrderStatusArgs {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n54(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FullOrder | null): [] | [_FullOrder] {
    return value === null ? candid_none() : candid_some(to_candid_FullOrder_n32(_uploadFile, _downloadFile, value));
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    deliveryAddress: Address;
    parcelPhoto?: ParcelPhoto;
    mobileNumber: string;
    dropLocation: string;
    pickupAddress: Address;
    paymentType: PaymentType;
    parcelDescription: string;
    pickupLocation: string;
}): {
    customerName: string;
    deliveryAddress: _Address;
    parcelPhoto: [] | [_ParcelPhoto];
    mobileNumber: string;
    dropLocation: string;
    pickupAddress: _Address;
    paymentType: _PaymentType;
    parcelDescription: string;
    pickupLocation: string;
} {
    return {
        customerName: value.customerName,
        deliveryAddress: value.deliveryAddress,
        parcelPhoto: value.parcelPhoto ? candid_some(value.parcelPhoto) : candid_none(),
        mobileNumber: value.mobileNumber,
        dropLocation: value.dropLocation,
        pickupAddress: value.pickupAddress,
        paymentType: to_candid_PaymentType_n29(_uploadFile, _downloadFile, value.paymentType),
        parcelDescription: value.parcelDescription,
        pickupLocation: value.pickupLocation
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    proofPhoto?: string;
    customerName: string;
    status: OrderStatus;
    deliveryAddress: string;
    assignedRider: Principal;
    customer: Principal;
    parcelPhoto?: ParcelPhoto;
    mobileNumber: string;
    dropLocation: string;
    pickupAddress: string;
    timestamp: Time;
    paymentType: Variant_cash_online;
    parcelDescription: string;
    pickupLocation: string;
}): {
    id: string;
    proofPhoto: [] | [string];
    customerName: string;
    status: _OrderStatus;
    deliveryAddress: string;
    assignedRider: Principal;
    customer: Principal;
    parcelPhoto: [] | [_ParcelPhoto];
    mobileNumber: string;
    dropLocation: string;
    pickupAddress: string;
    timestamp: _Time;
    paymentType: {
        cash: null;
    } | {
        online: null;
    };
    parcelDescription: string;
    pickupLocation: string;
} {
    return {
        id: value.id,
        proofPhoto: value.proofPhoto ? candid_some(value.proofPhoto) : candid_none(),
        customerName: value.customerName,
        status: to_candid_OrderStatus_n34(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        assignedRider: value.assignedRider,
        customer: value.customer,
        parcelPhoto: value.parcelPhoto ? candid_some(value.parcelPhoto) : candid_none(),
        mobileNumber: value.mobileNumber,
        dropLocation: value.dropLocation,
        pickupAddress: value.pickupAddress,
        timestamp: value.timestamp,
        paymentType: to_candid_variant_n30(_uploadFile, _downloadFile, value.paymentType),
        parcelDescription: value.parcelDescription,
        pickupLocation: value.pickupLocation
    };
}
function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: Role;
}): {
    name: string;
    role: _Role;
} {
    return {
        name: value.name,
        role: to_candid_Role_n55(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: OrderStatus;
    orderId: OrderId;
}): {
    status: _OrderStatus;
    orderId: _OrderId;
} {
    return {
        status: to_candid_OrderStatus_n34(_uploadFile, _downloadFile, value.status),
        orderId: value.orderId
    };
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_cash_online): {
    cash: null;
} | {
    online: null;
} {
    return value == Variant_cash_online.cash ? {
        cash: null
    } : value == Variant_cash_online.online ? {
        online: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    new: null;
} | {
    assigned: null;
} | {
    picked: null;
} | {
    delivered: null;
} {
    return value == OrderStatus.new ? {
        new_: null
    } : value == OrderStatus.assigned ? {
        assigned: null
    } : value == OrderStatus.picked ? {
        picked: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value;
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    customer: null;
} | {
    rider: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.customer ? {
        customer: null
    } : value == Role.rider ? {
        rider: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
